import argparse, io, os, tempfile, unittest
from npsv.sample import Sample
from npsv import npsva

FILE_DIR = os.path.join(os.path.dirname(__file__), "data")

class FilterSyntheticReadsTest(unittest.TestCase):

  def test_filter_reads(self):
    self.assertTrue(True)
    # ref-1045\t83\tref\t4255\t99\t148=\t=\t4006\t-397\tCCAGCGTCCCAGTGTGGGTGGCGTTTGCCTGGGCTGGGTACTGAGGCCGAGGTCCCCGCCACATCGTGGGCTCTGGGGTTAGGGCTGGGGAGGACAGCCTTGCCCCCGAGTGCGCTGACTGTCTTGGCCGTCTAGGGGGCATGTGGCC\tCGGCCG8C=GGGGGGGGGCGGGGCGGCGGGG1GGCGGGGG=CGCGGCGCCGGGCCGGCGGGGGGCG=GGGGGCGG(GCCJGGCGGJJJGJCJGJGGGGCGJ=CCGJJJJJJJGGJJGCJJGGJGJCGCJ=GJJJJGGGGGGGGG=C=C\nref-1045\t163\tref\t4006\t99\t148=\t=\t4255\t397\tTTGTAGTGGGTGCACACGCGTGCACTGGGACCCCACACAGCAATACGAGTCCAACTTAATAAACACATTTCTGGGGTTCCTCAGGCTGAGCATCTCTCTCTGGCATGTGGGGCAGCTGCGCAACTTTGGGTCCTGTCTGGGGTCCAGG\tCCCGGGGCGGGGGJGGJJJJGJ1JJJJJGJC==GJJCGJJGJGCGJGJGGJJJJGGGGGJJGJJGGGGGGCGGGJGGGGCGC8GGG=C8CCGG=GGGGC=GCJGCGGGCCG=GGGCGGGGCGGGGGCCCGGGGGG=GCGGCGGGGG=C\n