#!/usr/bin/env python3
import argparse, logging, os, re, sys
import pysam
import vcf

def _flatten(scalar_or_list):
    if isinstance(scalar_or_list, list):
        return scalar_or_list[0]
    else:
        return scalar_or_list


def makeArgParser():
    """
    Returns an argument parser parser with the command line arguments
    """
    parser = argparse.ArgumentParser(
        description="Annotate SV VCF with END, SVLEN, etc.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "-i", "--input", type=str, help="Path to input vcf file", required=True
    )
    parser.add_argument(
        "-o",
        "--output",
        action="store",
        type=argparse.FileType("w"),
        default=sys.stdout,
        help="Output file",
    )
    parser.add_argument(
        "--symbolic",
        help="Convert sequence resolved variants to symbolic alleles",
        action="store_true",
        default=False,
    )
    parser.add_argument(
        "-r",
        "--reference-sequence",
        help="Reference fasta file",
        type=str,
        dest="reference",
        required=True,
    )
    parser.add_argument(
        "--alt-field",
        help="Set alt from this INFO field (used for insertions)",
        type=str,
        default=None
    )
    return parser


def main(args):
    # Load the reference FASTA
    fasta = pysam.FastaFile(args.reference)
    
    vcf_reader = vcf.Reader(filename=args.input)
    
    vcf_reader.infos["END"] = vcf.parser._Info("END", 1, "Integer", "End position of the variant described in this record", None, None)   
    vcf_reader.infos["SVTYPE"] = vcf.parser._Info("SVTYPE", 1, "String", "Type of structural variant", None, None)   
    vcf_reader.infos["SVLEN"] = vcf.parser._Info("SVLEN", ".", "Integer", "Difference in length between REF and ALT alleles", None, None)   
    
    vcf_writer = vcf.Writer(args.output, vcf_reader)
    for record in vcf_reader:
        assert len(record.ALT) == 1, "Multiple alternates are not supported"
        allele = record.ALT[0]
        
        if isinstance(allele, vcf.model._SV) and "SVLEN" not in record.INFO:
            if "END" not in record.INFO:
                # Missing necessary information for SV, skip...
                continue
            type = record.var_subtype
            if type.startswith("DEL"):
                record.INFO["SVLEN"] = -(int(record.INFO["END"]) - int(record.POS))
            elif type.startswith("DUP"):
                record.INFO["SVLEN"] = int(record.INFO["END"]) - int(record.POS)
            else:
                print(record)
                assert False, "Unsupported variant type"
            
        elif "SVLEN" not in record.INFO or "END" not in record.INFO:
            expected_end = record.POS + len(str(record.REF)) - 1
            record.INFO["END"] = expected_end
            
            expected_svlen = len(str(allele)) - len(str(record.REF))
            record.INFO["SVLEN"] = expected_svlen

            # Used with SV-plaudit dataset to facilitate annotation (since some genotypers only report
            # symbolic alleles)
            if args.symbolic:
                # This is brittle (doesn't handle SVs without padding base)
                record.ALT = [vcf.model._SV(record.var_subtype)]
                record.REF = record.REF[0]
                

        if isinstance(allele, vcf.model._SV) and record.var_subtype.startswith("DUP"):
            inserted_sequence = fasta.fetch(record.CHROM, record.POS - 1, record.sv_end)
            
            # Update the variant with the sequence
            record.INFO["SVTYPE"] = "INS"
            record.INFO["END"] = record.POS
            record = vcf.model._Record(
                record.CHROM,
                record.POS,
                record.ID,
                inserted_sequence[0],
                [vcf.model._Substitution(inserted_sequence)],
                record.QUAL,
                record.FILTER,
                record.INFO,
                record.FORMAT,
                record._sample_indexes,
                record.samples,
            )

        if args.alt_field is not None and isinstance(allele, vcf.model._SV) and record.var_subtype.startswith("INS") and args.alt_field in record.INFO:
            svlen = _flatten(record.INFO["SVLEN"])
            inserted_sequence = record.INFO[args.alt_field]
            if len(inserted_sequence) != svlen or record.POS != record.INFO["END"]:
                continue
           
            record = vcf.model._Record(
                record.CHROM,
                record.POS,
                record.ID,
                record.REF,
                [vcf.model._Substitution(record.REF + inserted_sequence.upper())],
                record.QUAL,
                record.FILTER,
                record.INFO,
                record.FORMAT,
                record._sample_indexes,
                record.samples,
            )

        vcf_writer.write_record(record)

if __name__ == "__main__":
    parser = makeArgParser()
    args = parser.parse_args()
    main(args)
