#!/usr/bin/env bash
set -e -o pipefail

TMPDIR_ROOT=$TMPDIR
REFERENCE=human_g1k_v37.fasta
SHAREDREF=
SAMPLE=
STATSFILE=
GNOMADCOVGFILE=

FLANK=1000
COVERAGE=20
FRAGMEAN=400
FRAGSD=121
LENGTH=150
PROFILE=HS25
ZYGOSITY=1
SAMPLES=1

usage()
{
    cat << EOF
usage: $(basename "$0") [options] IN_VCF OUT_BAM 

Generate synthetic BAMs for single variant and specified zygosity

Options:
  -h            Print this message
  -R FASTA      Path to reference file, default: $REFERENCE
  -S FASTA      Reference file already in shared memory, default: undefined
  -c integer    Haploid coverage, default: $COVERAGE
  -m float      Mean fragment size, default: $FRAGMEAN
  -s float      Standard deviation of fragment size, default: $FRAGSD
  -t DIRECTORY  Root for temporary directory, default: /data/scratch/\$USER 
  -l integer    Read length, default: $LENGTH
  -p string     ART sequencer profile, default: $PROFILE
  -z (0,1,2)    Alternate allele count (AC), default: $ZYGOSITY
  -f integer    Flank size, default: $FLANK
  -i integer    Number of samples in output SAM/BAM, default: $SAMPLES
  -n string     Sample name, default: undefined
  -j FILE       NPSV stats file for GC normalized coverage, default: undefined
  -g FILE       Path to gnomAD coverage file, default: undefined
EOF
}

while getopts "hR:S:c:m:s:t:l:p:z:f:i:p:n:g:j:" Option
do
    case $Option in
        R)
            REFERENCE=$OPTARG
            ;;
        S)
            SHAREDREF=$OPTARG
            ;;
        c)
            COVERAGE=$OPTARG
            ;;
        m)
            FRAGMEAN=$OPTARG
            ;;
        s)
            FRAGSD=$OPTARG
            ;;
        t)
            TMPDIR_ROOT=$OPTARG
            ;;
        l)
            LENGTH=$OPTARG
            ;;
        p)
            PROFILE=$OPTARG
            ;;
        z)
            ZYGOSITY=$OPTARG
            ;;
        f)
            FLANK=$OPTARG
            ;;
        i)
            SAMPLES=$OPTARG
            ;;
        n)
            SAMPLE=$OPTARG
            ;;
        g)
            GNOMADCOVGFILE=$OPTARG
            ;;
        j)
            STATSFILE=$OPTARG
            ;;
        h)
            usage
            exit 0
            ;;
        ?)
            usage
            exit 85
            ;;
    esac
done

shift $((OPTIND-1))
if [[ $# -ne 2 ]]; then
    >&2 echo "Error: Missing positional arguments"
    >&2 usage
    exit 1
fi

INVCF=$1
OUTBAM=$2

if [[ ! -e "$INVCF" ]]; then
    >&2 echo "Error: Input VCF file $INVCF does not exist"
    >&2 usage
    exit 1
fi

TMPDIR=$(mktemp -d --tmpdir="$TMPDIR_ROOT") || exit 1
trap "rm -rf $TMPDIR" 0

# Generate diploid FASTAs for input to synthetic read generator

FASTA=$TMPDIR/diploid.fasta
if [[ $ZYGOSITY -eq 0 ]]; then
    npsvg consensus -r "$REFERENCE" --flank "$FLANK" --ac 0 -i "$INVCF" -o "$FASTA"
    COVERAGE=$(bc <<< "$COVERAGE * 2")
elif [[ $ZYGOSITY -eq 1 ]]; then
    npsvg consensus -r "$REFERENCE" --flank "$FLANK" --ac 1 -i "$INVCF" -o "$FASTA"
elif [[ $ZYGOSITY -eq 2 ]]; then
    npsvg consensus -r "$REFERENCE" --flank "$FLANK" --ac 2 -i "$INVCF" -o "$FASTA"
    COVERAGE=$(bc <<< "$COVERAGE * 2")
else
    >&2 echo "Error: Invalid zygosity specified, required values are (0,1,2)"
    exit 1
fi
cp "$FASTA" "${OUTBAM/%bam/synth.fasta}"

# If gnomAD coverage file is provided, generate coverage profile
COVGPROFILE="${OUTBAM/%bam/coverage.fasta}"
if [[ -n $GNOMADCOVGFILE ]]; then
    npsvg covgprofile --flank "$FLANK" --gnomad-covg "$GNOMADCOVGFILE" -i "$INVCF" -o "$COVGPROFILE"
fi

# If shared memory reference is not defined, use reference files
if [[ -z $SHAREDREF ]]; then
    SHAREDREF="$REFERENCE"
fi

for (( s=1; s<=SAMPLES; s++ ))
do
    if [[ -z $SAMPLE ]]; then
        SM="synth${s}"
    else
        SM="$SAMPLE"
    fi
    # Generate synthetic reads reads1.fq and reads2.fq. art_illumina use time in seconds for seed which can result in identical seeds for data.
    READS_PREFIX=$TMPDIR/reads.synth${s}
    art_illumina -q -i "$FASTA" -o "$READS_PREFIX" -sam -ss "$PROFILE" -l "$LENGTH" -f "$COVERAGE" -p -m "$FRAGMEAN" -s "$FRAGSD" -sp -rs $(od -An -tu4 -N4 /dev/urandom) 1>&2
    
    >&2 echo "Generating aligned BAM"
    # Generate synthetic aligned BAM using minimal, but representative, pipeline
    # This pipeline should be modified to make the simulated pipeline similar to the
    # the pipeline used with the actual data
    ALIGNEDBAM=$TMPDIR/aligned${s}.bam
    
    if [[ -n $GNOMADCOVGFILE ]]; then
        # Downsample reads based on GnomAD data
        npsvg gnomadcovg --covg-path "$COVGPROFILE" -i "${READS_PREFIX}.sam" | \
        bwa mem -p -c 250 -M -v 1 -I "${FRAGMEAN},${FRAGSD}" \
            -R "@RG\tID:synth${s}\tSM:${SM}\tLB:synth${s}\tPL:illumina\tPU:ART" \
            "$SHAREDREF" \
            /dev/stdin | \
        samblaster -q -M --addMateTags | \
        samtools view -S -u  - | \
        sambamba -q sort -t 1 -m 512MiB --tmpdir="$TMPDIR" -o "$ALIGNEDBAM" /dev/stdin
    elif [[ -n $STATSFILE ]]; then
        # Downsample reads based on GC fraction
        npsvg normcovg --fasta-path "$FASTA" --stats-path "$STATSFILE" -i "${READS_PREFIX}.sam" | \
        bwa mem -p -c 250 -M -v 1 -I "${FRAGMEAN},${FRAGSD}" \
            -R "@RG\tID:synth${s}\tSM:${SM}\tLB:synth${s}\tPL:illumina\tPU:ART" \
            "$SHAREDREF" \
            /dev/stdin | \
        samblaster -q -M --addMateTags | \
        samtools view -S -u  - | \
        sambamba -q sort -t 1 -m 512MiB --tmpdir="$TMPDIR" -o "$ALIGNEDBAM" /dev/stdin
    else
        bwa mem -c 250 -M -v 1 -I "${FRAGMEAN},${FRAGSD}" \
            -R "@RG\tID:synth${s}\tSM:${SM}\tLB:synth${s}\tPL:illumina\tPU:ART" \
            "$SHAREDREF" \
            "${READS_PREFIX}1.fq" "${READS_PREFIX}2.fq" | \
        samblaster -q -M --addMateTags | \
        samtools view -S -u  - | \
        sambamba -q sort -t 1 -m 512MiB --tmpdir="$TMPDIR" -o "$ALIGNEDBAM" /dev/stdin
    fi
done

if [[ "$SAMPLES" -gt 1 ]]; then
    # Combine all of the individual BAM files
    >&2 echo "Generating aligned BAM files with replicates"
    sambamba -q merge -t 1 "$OUTBAM" $(seq 1 "$SAMPLES" | xargs printf " $TMPDIR/aligned%d.bam")
else
    mv "$TMPDIR/aligned1.bam" "$OUTBAM"
    mv "$TMPDIR/aligned1.bam.bai" "$OUTBAM.bai"
fi
>&2 echo "Completed generating synthetic data"